# STEP ONE: DATA ACQUISITION AND MANIPULATION

In [9]:
# Importing the necessary libraries
import pandas as pd
import datetime as dt

### OVERVIEW OF COLUMNS IN THE "GOONS" SHEET
| COLUMN | DESCRIPTION | EXAMPLE |
| ----------- | ----------- | ------- |
| ATHLETE | The athlete to whom the activity belongs. | "PATRICK L" |
| ACTIVITY ID | The identifier (ID) of the activity extracted. | 8963381312 |
| RUN | The name (i.e. title). | "WarmUp+3x1M MP/1'R + Strides" |        
| MOVING TIME | The moving time (HH:MM:SS). | "00:48:05" |
| DISTANCE | The distance (00.00). | 5.75 |
| PACE | The pace (HH:MM:SS). | "00:08:30" |        
| FULL DATE | The date (MM/DD/YYYY). | "4/26/2023" |        
| TIME | The time (HH:MM:SS AM/PM). | "6:10:12 PM" |        
| DAY | The weekday. | "WED" |        
| MONTH | The month. | 4 |        
| DATE | The day of the month. | 26 |        
| YEAR | The year. | 2023 |        
| SPM AVG | The average number of strides per minute (i.e. cadence). | 167 |        
| HR AVG | The average heart rate (in beats/minute). | 145.4 |        
| WKT TYPE | The run type (0 = None, 1 = Race, 2 = Long run, 3 = Workout). | 3 |        
| DESCRIPTION | The description, or caption. | "Bitch it ain't even my birthday, but I can ball if I want to." |        
| TOTAL ELEV GAIN | The total elevation gain (in meters). | 77.5 |        
| MANUAL | Whether the run was manual or not. | "FALSE" |
| MAX SPEED | The highest speed (in meters/second). | 5.171 |                
| CALORIES | The number of calories burned. | 622 |                
| ACHIEVEMENT COUNT | The number of achievements gained (e.g. Strava PRs). | 0 |                
| KUDOS COUNT | The number of kudos received. | 3 |                
| COMMENT COUNT | The number of comments received. | 3 |                
| ATHLETE COUNT | The number of (identified) athletes run with. | 1 |

In [10]:
# Reading in the CSV file and displaying the first five activities
activities_df = pd.read_csv("C:/Users/17178/Desktop/GITHUB_PROJECTS/Strava-API-and-Sheets-Integration/python/data/GOONS_ACTIVITIES.csv", header=0)
activities_df.head(5)

,ATHLETE,ACTIVITY ID,RUN,MOVING TIME,DISTANCE,PACE,FULL DATE,TIME,DAY,MONTH,...,WKT TYPE,DESCRIPTION,TOTAL ELEV GAIN,MANUAL,MAX SPEED,CALORIES,ACHIEVEMENT COUNT,KUDOS COUNT,COMMENT COUNT,ATHLETE COUNT
0,ME,9388321572,Afternoon Run,00:30:00,4.29,00:07:00,7/4/2023,1:09:32 PM,TUE,7,...,0.0,brutal out there 🫠 rocked the us flag boa shor...,31.0,False,5.147,516.0,0.0,19.0,2.0,1.0
1,PATRICK L,9387226010,WarmUp+Run+HILLS,01:07:03,7.07,00:09:33,7/4/2023,10:09:05 AM,TUE,7,...,3.0,"Kept pace Easy-Steady.\nHILLS: 8x30"" hill spri...",106.8,False,5.010,852.0,0.0,14.0,0.0,1.0
2,MARK M,9386435707,Morning Run,00:59:03,8.03,00:07:24,7/4/2023,8:18:01 AM,TUE,7,...,0.0,Another good run w Jake,48.0,False,6.476,0.0,5.0,14.0,0.0,2.0
3,PATRICK B,9383051907,Workout and hill sprints!,00:57:04,8.01,00:07:13,7/3/2023,3:53:27 PM,MON,7,...,0.0,-5k tempo & 5:51 pace\n-4x20s hills,199.0,False,7.048,654.0,0.0,11.0,1.0,1.0
4,TIMMY B,9382709958,Hot,00:50:04,6.41,00:07:55,7/3/2023,2:51:26 PM,MON,7,...,0.0,NaN,158.2,False,4.844,671.0,2.0,9.0,0.0,1.0

In [11]:
print(activities_df["WKT TYPE"].unique())

[ 0.  3.  2. nan  1.]

In [12]:
# Converting WKT TYPE to be an int
activities_df.loc[activities_df["WKT TYPE"].isna() | activities_df["WKT TYPE"].isnull(), "WKT TYPE"] = activities_df["WKT TYPE"].mask(activities_df["WKT TYPE"].isna() | activities_df["WKT TYPE"].isnull(), "0")
activities_df["WKT TYPE"] = activities_df["WKT TYPE"].astype("int").astype("category")

# Converting full date to a sortable format
activities_df["FULL DATE"] = pd.to_datetime(activities_df["FULL DATE"], yearfirst=False, dayfirst=False).dt.date

# Converting moving time to a sortable (and arithmetically-friendly) format
activities_df['MOVING TIME'] = pd.to_datetime(activities_df['MOVING TIME'], format='%H:%M:%S').dt.time

# Converting time to a sortable (24h) format (for new column, "24H TIME")
activities_df["24H TIME"] = pd.to_datetime(activities_df["TIME"], format='%I:%M:%S %p').dt.time

# Sorting the dataframe by full date and time in descending order
activities_df = activities_df.sort_values(by=["FULL DATE", "24H TIME"], ascending=[False, False]) # Extra precaution (things should be sorted properly as is)

In [13]:
activities_df.head(3)

,ATHLETE,ACTIVITY ID,RUN,MOVING TIME,DISTANCE,PACE,FULL DATE,TIME,DAY,MONTH,...,DESCRIPTION,TOTAL ELEV GAIN,MANUAL,MAX SPEED,CALORIES,ACHIEVEMENT COUNT,KUDOS COUNT,COMMENT COUNT,ATHLETE COUNT,24H TIME
0,ME,9388321572,Afternoon Run,00:30:00,4.29,00:07:00,2023-07-04,1:09:32 PM,TUE,7,...,brutal out there 🫠 rocked the us flag boa shor...,31.0,False,5.147,516.0,0.0,19.0,2.0,1.0,13:09:32
1,PATRICK L,9387226010,WarmUp+Run+HILLS,01:07:03,7.07,00:09:33,2023-07-04,10:09:05 AM,TUE,7,...,"Kept pace Easy-Steady.\nHILLS: 8x30"" hill spri...",106.8,False,5.010,852.0,0.0,14.0,0.0,1.0,10:09:05
2,MARK M,9386435707,Morning Run,00:59:03,8.03,00:07:24,2023-07-04,8:18:01 AM,TUE,7,...,Another good run w Jake,48.0,False,6.476,0.0,5.0,14.0,0.0,2.0,08:18:01

In [14]:
# Viewing data types of each column
activities_df.dtypes

ATHLETE                object
ACTIVITY ID             int64
RUN                    object
MOVING TIME            object
DISTANCE              float64
PACE                   object
FULL DATE              object
TIME                   object
DAY                    object
MONTH                   int64
DATE                    int64
YEAR                    int64
SPM AVG               float64
HR AVG                float64
WKT TYPE             category
DESCRIPTION            object
TOTAL ELEV GAIN       float64
MANUAL                 object
MAX SPEED             float64
CALORIES              float64
ACHIEVEMENT COUNT     float64
KUDOS COUNT           float64
COMMENT COUNT         float64
ATHLETE COUNT         float64
24H TIME               object
dtype: object

### INITIAL DATA INSIGHTS

In [27]:
# TODO: Gather interesting, higher-level basic insights on each athlete (e.g. getting average pace graph)
df_pat = activities_df[activities_df["ATHLETE"] == "PATRICK L"]
df_pat = df_pat[df_pat["WKT TYPE"] == 0]
df_pat[["SPM AVG", "HR AVG", "MAX SPEED"]].mean().round(2) # Just getting averages for some basic numerical columns

SPM AVG      162.62
HR AVG       135.73
MAX SPEED      3.97
dtype: float64

### MACHINE LEARNING

In [16]:
# TODO: 
# 1) Clean out unhelpful/inappropriate data (determine what that means)
        # We might not want data that has NA values (NA HR, MANUAL RUNS, ETC.) - This could mean losing an entire set of data for an athlete (for HR).
            # Certainly omit the manual runs, if any exist.
        # We should probably omit warmup and cooldown runs from workout days for those who do that.
            # Detecting this would involve checking the runs done on a given day for a given athlete and seeing if there were multiple around the same time.
                # If that's the case, and WKT TYPE is 3 (better yet), we can be confident that the shorter runs (1st and 3rd) are WU and CD and omit such activities.
        # Do we want to require HR, or should we just ignore that altogether? I think we could gain some good insights from it.
        # We can probably omit the following columns:
            # ACTIVITY ID (irrelevant)
            # RUN (uninterpretable string)
            # DAY, MONTH, DATE (if needed, we can extract such fields from FULL DATE)
            # TIME (uninterpretable unlike 24H TIME)
            # DESCRIPTION (uninterpretable string)
            # THE FOUR COUNT VARIABLES (we could keep them, I'd be interested to see if they play a part in training)
                # Theory: It could help athletes to stay motivated. That is, receiving kudos, comments, having people to run with, and achievements.
                # Caveat: The counts could be inaccurate and out-of-date. An activity could be extracted not long after being posted,
                    # in which case the counts would be lower than if it were extracted later. We'd essentially have to update these for a lot of the rows.
# 2) Add more columns per the google doc (for this ML) and do any further cleaning as necessary
    # Days run from last X days, mileage from last X days, time from last X days, average HR from last X days, ...
# 3) Think through what columns would be useful here and create a new DataFrame with only those valuable (and interpretable) predictors
# 4) Test out some ML modeling on what we got and make any necessary revisions
    # We're shooting for model 2 for now
# 5) Finalize a model