# STEP ONE: DATA ACQUISITION AND MANIPULATION

In [120]:
# Importing the necessary libraries
import pandas as pd
import datetime as dt

### OVERVIEW OF COLUMNS IN THE "GOONS" SHEET
| COLUMN | DESCRIPTION | EXAMPLE |
| ----------- | ----------- | ------- |
| ATHLETE | The athlete to whom the activity belongs. | "PATRICK L" |
| ACTIVITY ID | The identifier (ID) of the activity extracted. | 8963381312 |
| RUN | The name (i.e. title). | "WarmUp+3x1M MP/1'R + Strides" |        
| MOVING TIME | The moving time (HH:MM:SS). | "00:48:05" |
| DISTANCE | The distance (00.00). | 5.75 |
| PACE | The pace (HH:MM:SS). | "00:08:30" |        
| FULL DATE | The date (MM/DD/YYYY). | "4/26/2023" |        
| TIME | The time (HH:MM:SS AM/PM). | "6:10:12 PM" |        
| DAY | The weekday. | "WED" |        
| MONTH | The month. | 4 |        
| DATE | The day of the month. | 26 |        
| YEAR | The year. | 2023 |        
| SPM AVG | The average number of strides per minute (i.e. cadence). | 167 |        
| HR AVG | The average heart rate (in beats/minute). | 145.4 |        
| WKT TYPE | The run type (0 = None, 1 = Race, 2 = Long run, 3 = Workout). | 3 |        
| DESCRIPTION | The description, or caption. | "Bitch it ain't even my birthday, but I can ball if I want to." |        
| TOTAL ELEV GAIN | The total elevation gain (in meters). | 77.5 |        
| MANUAL | Whether the run was manual or not. | "FALSE" |
| MAX SPEED | The highest speed (in meters/second). | 5.171 |                
| CALORIES | The number of calories burned. | 622 |                
| ACHIEVEMENT COUNT | The number of achievements gained (e.g. Strava PRs). | 0 |                
| KUDOS COUNT | The number of kudos received. | 3 |                
| COMMENT COUNT | The number of comments received. | 3 |                
| ATHLETE COUNT | The number of (identified) athletes run with. | 1 |

In [121]:
# Reading in the CSV file and displaying the first five activities
activities_df = pd.read_csv("C:/Users/17178/Desktop/GITHUB_PROJECTS/Strava-API-and-Sheets-Integration/python/data/GOONS_ACTIVITIES.csv", header=0)
activities_df.head(5)

,ATHLETE,ACTIVITY ID,RUN,MOVING TIME,DISTANCE,PACE,FULL DATE,TIME,DAY,MONTH,...,WKT TYPE,DESCRIPTION,TOTAL ELEV GAIN,MANUAL,MAX SPEED,CALORIES,ACHIEVEMENT COUNT,KUDOS COUNT,COMMENT COUNT,ATHLETE COUNT
0,PATRICK L,8963381312,WarmUp+3x1M MP/1'R + Strides,00:48:05,5.75,00:08:30,4/26/2023,6:10:12 PM,WED,4,...,3.0,Last little workout before race.\nHit MP at 55...,77.5,False,5.171,622.0,0.0,3.0,3.0,1.0
1,ME,8963204543,Afternoon Run,00:37:05,4.12,00:09:12,4/26/2023,5:40:51 PM,WED,4,...,0.0,"5x5/1, no alpha pull ups bc bar was wet from r...",37.0,False,4.852,482.0,0.0,8.0,3.0,1.0
2,MARK M,8962844658,Afternoon Run,00:40:04,5.39,00:07:33,4/26/2023,4:02:47 PM,WED,4,...,NaN,NaN,96.6,False,6.616,0.0,2.0,8.0,0.0,1.0
3,DAVID L,8959623291,Down,00:19:00,2.01,00:09:31,4/26/2023,6:41:45 AM,WED,4,...,0.0,Feelin groovy. We’ll call today 7.,22.0,False,4.400,282.0,0.0,6.0,0.0,1.0
4,DAVID L,8959623154,Olé,00:22:01,2.90,00:07:39,4/26/2023,6:12:23 AM,WED,4,...,3.0,"20’ threshold, 2’ rest, 4x 20” hills. Thresho...",28.0,False,5.500,416.0,4.0,13.0,0.0,1.0

In [122]:
# Converting WKT TYPE to be an int
activities_df.loc[activities_df["WKT TYPE"].isna() | activities_df["WKT TYPE"].isnull(), "WKT TYPE"] = activities_df["WKT TYPE"].mask(activities_df["WKT TYPE"].isna() | activities_df["WKT TYPE"].isnull(), "0")
activities_df["WKT TYPE"] = activities_df["WKT TYPE"].astype("int").astype("category")

# Converting full date to a sortable format
activities_df["FULL DATE"] = pd.to_datetime(activities_df["FULL DATE"], yearfirst=False, dayfirst=False).dt.date

# Converting moving time to a sortable (and arithmetically-friendly) format
activities_df['MOVING TIME'] = pd.to_datetime(activities_df['MOVING TIME'], format='%H:%M:%S').dt.time

# Converting time to a sortable (24h) format (for new column, "24H TIME")
activities_df["24H TIME"] = pd.to_datetime(activities_df["TIME"], format='%I:%M:%S %p').dt.time

# Sorting the dataframe by full date and time in descending order
activities_df = activities_df.sort_values(by=["FULL DATE", "24H TIME"], ascending=[False, False]) # Extra precaution (things should be sorted properly as is)

In [123]:
activities_df.head(3)

,ATHLETE,ACTIVITY ID,RUN,MOVING TIME,DISTANCE,PACE,FULL DATE,TIME,DAY,MONTH,...,DESCRIPTION,TOTAL ELEV GAIN,MANUAL,MAX SPEED,CALORIES,ACHIEVEMENT COUNT,KUDOS COUNT,COMMENT COUNT,ATHLETE COUNT,24H TIME
0,PATRICK L,8963381312,WarmUp+3x1M MP/1'R + Strides,00:48:05,5.75,00:08:30,2023-04-26,6:10:12 PM,WED,4,...,Last little workout before race.\nHit MP at 55...,77.5,False,5.171,622.0,0.0,3.0,3.0,1.0,18:10:12
1,ME,8963204543,Afternoon Run,00:37:05,4.12,00:09:12,2023-04-26,5:40:51 PM,WED,4,...,"5x5/1, no alpha pull ups bc bar was wet from r...",37.0,False,4.852,482.0,0.0,8.0,3.0,1.0,17:40:51
2,MARK M,8962844658,Afternoon Run,00:40:04,5.39,00:07:33,2023-04-26,4:02:47 PM,WED,4,...,NaN,96.6,False,6.616,0.0,2.0,8.0,0.0,1.0,16:02:47

In [124]:
# Viewing data types of each column
activities_df.dtypes

ATHLETE                object
ACTIVITY ID             int64
RUN                    object
MOVING TIME            object
DISTANCE              float64
PACE                   object
FULL DATE              object
TIME                   object
DAY                    object
MONTH                   int64
DATE                    int64
YEAR                    int64
SPM AVG               float64
HR AVG                float64
WKT TYPE             category
DESCRIPTION            object
TOTAL ELEV GAIN       float64
MANUAL                 object
MAX SPEED             float64
CALORIES              float64
ACHIEVEMENT COUNT     float64
KUDOS COUNT           float64
COMMENT COUNT         float64
ATHLETE COUNT         float64
24H TIME               object
dtype: object

In [ ]:
# TODO: 
# 1) Clean out unhelpful/inappropriate data (determine what that means) 
# 2) Add more columns per the google doc (for this ML) and do any further cleaning as necessary
# 3) Think through what columns would be useful here and create a new DataFrame with only those valuable (and interpretable) predictors
# 4) Test out some ML modeling on what we got and make any necessary revisions
# 5) Finalize a model